language: ruby
rvm:
- 2.1

install: gem install jekyll pygments.rb html-proofer
script: jekyll build && htmlproof ./_site --href-ignore '//blog/\#[a-z]+/' --disable-external

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
