language: ruby
rvm:
- 2.4

install: gem install jekyll pygments.rb html-proofer
script: jekyll build && htmlproofer ./_site --url-ignore '//blog/\#[A-Za-z]+/' --disable-external

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
