name: Vaclav Dedik
timezone: Europe/Prague
permalink: /blog/:title/
highlighter: pygments
markdown: kramdown
exclude: [vendor, README.md]
url: http://vaclavdedik.com
navigation:
- text: Home
  url: /
- text: Blog
  url: /blog/
defaults:
  -
    scope:
        path: ""
        type: "posts"
    values:
        layout: post
        subtitle: "Václav Dedík's Blog"
        nav_group: /blog/
